import sys
sys.path.append("../..")
import plantbox as pb
import rsml_reader_px as rsml
import estimate_params as es
import math
import numpy as np

times = [130]  # not in the rsml
polylines, properties, functions = rsml.read_rsml("Maize_Kutschera.rsml")

print("Summary\n*******")
print("Number of roots", len(polylines))
print("\nproperties")
for key in properties.keys():
    print(key)
print("\nfunctions")
for key in functions.keys():
    print(key)
print()

#fet = functions["emergence_time"] 
fd = functions["diameter"]

pp = properties["parent-poly"]  # generated by read_rsml
pn = properties["parent-node"]  
pl = properties["length"]
pia = properties["insertion-angle"]

rsml.plot_rsml(polylines, pia) # looks good

basepolys = []
basetypes = []
baseindices = []
pi = []  # index of the corresponding base root 
#pet = []

for i, p in enumerate(polylines):
    pi.append(es.find_base_index(pp, i))
    #pet.append(fet[i][0])
    if pp[i] == -1: 
        baseindices.append(i)
        basepolys.append(p)
        #basetypes.append(pt[i])  # have type = 0, but there are more
        
#nppt = np.array(pt)
#print(len(basepolys), "base roots found, ", np.sum(nppt == 1.), " type 1 roots fouond")  # ? genau doppelt soviel, zufall?

# print(baseindices)
# print(pi)  # already sorted by base root
#rsml.plot_rsml(basepolys, basetypes)  # looks all right
print("fin.")

