#!/bin/bash
#submit a chain of jobs





cc=1
while [ $cc -le 20 ];
do


    cd /home/m.landl/CPlantBox/tutorial/examples/phase1	
    cat <<EOF> simulation$cc.pbs

#!/bin/sh
#PBS -N simulation$cc
#PBS -l nodes=1:ppn=2,walltime=100:00:00,vmem=240gb
#PBS -q openmp
#PBS -M m.landl@fz-juelich.de
#PBS -m e

cd /home/m.landl/CPlantBox/tutorial/examples/phase1
module load python-3.8
module load dumux 
python3 rasterize$cc.py


EOF

      /usr/bin/qsub simulation$cc.pbs	
      let cc=$cc+1


done	

