FROM quay.io/pypa/manylinux2014_aarch64

RUN yum -y install mesa-libGLU mesa-libGL-devel mesa-dri-drivers libXrender libXext libSM xorg-x11-server-Xvfb && yum clean all || true

RUN /opt/python/cp310-cp310/bin/pip install -U pip pytest vtk==9.5.0

WORKDIR /project

