@startuml
footer Arnaud Bouvry
' Ortho lines (only vertical and horizontal segments)
'skinparam linetype ortho

' Split into 4 pages
'page 2x2
'skinparam pageMargin 10

skinparam svgLinkTarget _parent


'#############
'# RANDOM PARAMETERS
'#############

class CPlantBox::OrganRandomParameter
class CPlantBox::LeafRandomParameter
class CPlantBox::RootRandomParameter
class CPlantBox::SeedRandomParameter
class CPlantBox::StemRandomParameter

CPlantBox::Vector3d <-- CPlantBox::SeedRandomParameter
note on link
seedPoss
seedPos
end note

CPlantBox::OrganRandomParameter <- CPlantBox::LeafRandomParameter
CPlantBox::OrganRandomParameter <- CPlantBox::RootRandomParameter
CPlantBox::OrganRandomParameter <- CPlantBox::SeedRandomParameter
CPlantBox::OrganRandomParameter <- CPlantBox::StemRandomParameter


' hidden lines for layout
CPlantBox::LeafRandomParameter <-[hidden]- CPlantBox::RootRandomParameter
CPlantBox::RootRandomParameter <-[hidden]- CPlantBox::SeedRandomParameter
CPlantBox::SeedRandomParameter <-[hidden]- CPlantBox::StemRandomParameter

'#############
'# SPECIFIC PARAMETERS
'#############

class CPlantBox::OrganSpecificParameter
class CPlantBox::LeafSpecificParameter
class CPlantBox::RootSpecificParameter
class CPlantBox::SeedSpecificParameter
class CPlantBox::StemSpecificParameter

CPlantBox::Vector3d <-- CPlantBox::SeedSpecificParameter
note on link
seedPos
end note

CPlantBox::OrganSpecificParameter <-- CPlantBox::LeafSpecificParameter
CPlantBox::OrganSpecificParameter <-- CPlantBox::RootSpecificParameter
CPlantBox::OrganSpecificParameter <-- CPlantBox::SeedSpecificParameter
CPlantBox::OrganSpecificParameter <-- CPlantBox::StemSpecificParameter

' hidden lines for layout
CPlantBox::LeafSpecificParameter <-[hidden]- CPlantBox::RootSpecificParameter
CPlantBox::RootSpecificParameter <-[hidden]- CPlantBox::SeedSpecificParameter
CPlantBox::SeedSpecificParameter <-[hidden]- CPlantBox::StemSpecificParameter
'CPlantBox::Vector3d <-[hidden] CPlantBox::OrganSpecificParameter

'#############
'# GEOMETRY
'#############

class CPlantBox::Matrix3d
class CPlantBox::Vector3d

CPlantBox::Vector3d <.. CPlantBox::Matrix3d
note on link
r0
r1
r2
end note

@enduml

